### ISSUE TITLE
Clarification on how to use the "fallback" option in partial search

### ISSUE THREAD

**Issue by ubendre** [ONSdigital/address-index-api#693]
As per the API docs, the "fallback" flag when set to true, means that a "Specifies whether a slow fallback query is used in the event of the main query returning no results.". I tested this API with a string in the "input" parameter, which does not have any address matching to it. It returned  "addresses": [], in the result, but I don't understand how the "fallback" option comes into play here? Should we specify a different query somewhere, as the query to use on fallback? 
Can the README for this API endpoint updated with more clarification?

**Comment by RichardSmithONS** [comment]
For the Census 2021 website, to support EQ (Electronic Questionnaire) we looked at both speed and user-friendliness of the _/partial_ endpoint (called via the _/eq_ custom endpoint). On Census day we were getting over 3,000 requests per second so just as well we went for speed as top priority:
- cutoff at 250ms for the ES query: This works well when the input string is short and the user is unlikely to want to select any of the results, so an incomplete result set is fine (ES will return whatever it has found in the time allowed).
- fallback flag set to off: This means the typeahead is unforgiving and a typo or misspelling is likely to mean no results. If the fallback flag is on, a fuzzy query is run which will usually give some results, but this takes rather too many milliseconds.

**Comment by ubendre** [comment]
I see in ElasticsearchRepositorySpec.scala the 250ms hardcoded. Is this the cutoff you are referring to?

Are the following, the fuzzy queries that would run when the 'fallback' flag is on? Only in one case below do I see the fallback being set to true in the code, i.e. the last one. So thats the default query that runs when the 250ms cutoff is breached, and fallback is set to true? Also at that point will the result include both those from the incomplete result set generated within 250ms and the result of the fallback query?

        input = "h4",
        filters = "residential",
        limit = 1,

        input = "12345",
        filters = "residential",
        limit = 1,

        input = "123456",
        filters = "residential",
        limit = 1,

        **_input = "h4",
        fallback = true,
        filters = "residential",
        limit = 1_**

**Comment by RichardSmithONS** [comment]
For speed, the typeahead search is done on a single conglomerated index field that contains all the unique words in all the versions of the formatted address (English PAF, English NAG [can be more than one], Welsh PAF, Welsh NAG) and uses an edge-ngram analyser. Phrase queries are very fast against this, but there is no fuzziness allowed. If the fallback flag is off, and no results are returned, that's it. If the fallback flag is on, in the event of no results being obtained from the initial query, another, more forgiving best_fields query is performed. All queries "bail out" at 250ms and return whatever they have.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html
best_fields: slow, more forgiving
phrase: fast, not fuzzy

https://github.com/ONSdigital/address-index-api/blob/develop/server/app/uk/gov/ons/addressIndex/server/modules/AddressIndexRepository.scala#L113

As I mentioned before, user testing showed that "off" is best, even though the user may have to backpedal when the character they typed results in no matches.

**Comment by ubendre** [comment]
Thanks @RichardSmithONS . This is very helpful.
