### ISSUE TITLE
addresses/multiuprn not available in docker based version

### ISSUE THREAD

**Issue by ubendre** [ONSdigital/address-index-api#695]
In the docker-compose based version I don't see the addresses/multiuprn route available in the /routes

**Comment by RichardSmithONS** [comment]
The API image is three years old. 
`  address-index-api:
    image: "thornsj/address-index-api:190420"`

**Comment by ubendre** [comment]
thanks. I don't see any newer docker images. Do you plan to publish a newer one anytime soon, otherwise we will build the project on our side.
